package pl.kamil_dywan.gui;

import pl.kamil_dywan.service.*;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.util.Optional;

public class MainGui {

    private JPanel mainPanel;

    private JTabbedPane tabbedPane;
    private final ProductsGui productsGui;
    private final OrdersGui ordersGui;
    private final LoginGui loginGui;

    private GridBagConstraints mainPanelLayoutConstrains;

    private final AuthService authService;
    private final BasicInfoService basicInfoService;

    private final JFrame frame;

    public MainGui(AuthService authService, ProductService productService, OrderService orderService, BasicInfoService basicInfoService) {

        this.authService = authService;
        this.basicInfoService = basicInfoService;

        loginGui = new LoginGui(authService, this::handleSuccessAuth);
        productsGui = new ProductsGui(productService, this::handleLogout);
        ordersGui = new OrdersGui(orderService, this::handleLogout);

        tabbedPane.addTab("Zamówienia", ordersGui.getMainPanel());
        tabbedPane.addTab("Produkty", productsGui.getMainPanel());

        loadMainPanelLayoutConstraints();

        frame = new JFrame("Integracja Allegro i Subiekt GT");

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(1200, 780);
        frame.setLocationRelativeTo(null);

        handleAuth();

        frame.add(mainPanel);

        frame.setVisible(true);
    }

    private void loadMainPanelLayoutConstraints() {

        mainPanelLayoutConstrains = new GridBagConstraints();

        mainPanelLayoutConstrains.gridx = 0;
        mainPanelLayoutConstrains.gridy = 0;
        mainPanelLayoutConstrains.fill = GridBagConstraints.BOTH;
        mainPanelLayoutConstrains.weightx = 1;
        mainPanelLayoutConstrains.weighty = 1;
    }

    private void handleAuth() {

        if (authService.doesUserPassedFirstLoginToApp() && authService.isUserLogged()) {

            handleSuccessAuth();
        } else {

            changeMainPanelContent(loginGui.getMainPanel());
        }
    }

    private void handleSuccessAuth() {

        loadMenu();

        productsGui.load();
        ordersGui.load();

        changeMainPanelContent(tabbedPane);
    }

    private void loadMenu() {

        JMenuBar menuBar = new JMenuBar();

        JMenu accountMenu = new JMenu("Konto");

        JMenuItem basicInfoMenuItem = new JMenuItem("Podstawowe informacje");
        basicInfoMenuItem.addActionListener(e -> handleBasicInfo());

        JMenuItem accountMenuItem = new JMenuItem("Wyloguj");
        accountMenuItem.addActionListener(e -> handleLogout());

        accountMenu.add(basicInfoMenuItem);
        accountMenu.add(accountMenuItem);

        menuBar.add(accountMenu);

        frame.setJMenuBar(menuBar);
    }

    private void changeMainPanelContent(Component component) {

        mainPanel.removeAll();
        mainPanel.add(component, mainPanelLayoutConstrains);

        mainPanel.revalidate();
        mainPanel.repaint();
    }

    private void handleBasicInfo() {

        Optional<String> existingLocation = basicInfoService.getLocation();

        String gotLocation = JOptionPane.showInputDialog("Wprowadź nazwę miejcowości sprzedawcy", existingLocation.orElse(""));

        if (gotLocation == null) {
            return;
        }

        basicInfoService.setLocation(gotLocation);

        JOptionPane.showMessageDialog(null, "Zapisano dane", "Powiadomienie", JOptionPane.INFORMATION_MESSAGE);
    }

    private void handleLogout() {

        frame.setJMenuBar(new JMenuBar());

        authService.logout();

        loginGui.handleLogout();
        changeMainPanelContent(loginGui.getMainPanel());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        tabbedPane = new JTabbedPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(tabbedPane, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
